### ISSUE TITLE
Superior figures are not superior

### ISSUE THREAD

**Issue by eweracs** [github/hubot-sans#15]
Somehow, the superior figures are the same as the inferior ones. Note: The inferior figures are sitting on the baseline, which is... odd, to say the least.

<img width="469" alt="image" src="https://github.com/github/hubot-sans/assets/51919489/7362f7aa-8a79-4043-8f07-93daafe08b5f">

**Comment by tobiasahlin** [comment]
Fixed in https://github.com/github/hubot-sans/pull/31 🙏
