### ISSUE TITLE
Period shifts in height between Roman and Italic

### ISSUE THREAD

**Issue by eweracs** [github/hubot-sans#23]
In the master Black Wide Italic, the `period` is smaller than in the Black Wide master. This does not appear to be a design choice, as a height difference is not present in any other Roman/Italic master pairs.

<img width="841" alt="image" src="https://github.com/github/hubot-sans/assets/51919489/28f70a51-b069-46a5-a574-062537609906">

**Comment by tobiasahlin** [comment]
Fixed in https://github.com/github/hubot-sans/pull/31 🙏
