### ISSUE TITLE
periodcentered.loclCAT does not have stylistic set variation

### ISSUE THREAD

**Issue by eweracs** [github/hubot-sans#25]
The default dots are square, ss01 is for rounded dots. The default periodcentered.loclCAT (+.case) is round. The default should be square, with a round alternative for ss01.

<img width="735" alt="image" src="https://github.com/github/hubot-sans/assets/51919489/0217d9e9-e756-4ce0-8a0b-cb43b5fa3c36">

**Comment by tobiasahlin** [comment]
Fixed in https://github.com/github/hubot-sans/pull/31 🙏
