### ISSUE TITLE
Eogonek, Iogonek.ss04: faulty design

### ISSUE THREAD

**Issue by eweracs** [github/hubot-sans#26]
The anchor is misplaced for the Eogonek.

<img width="617" alt="image" src="https://github.com/github/hubot-sans/assets/51919489/50caec03-fdbc-4b5f-83b7-4515eb24ac69">

In Iogonek.ss04 as well.
<img width="323" alt="image" src="https://github.com/github/hubot-sans/assets/51919489/17b0aa51-8337-44bd-a7b8-ccb5ff727418">

**Comment by tobiasahlin** [comment]
Fixed in https://github.com/github/hubot-sans/pull/31 🙏
