### ISSUE TITLE
I.ss01 diacritics are wrong

### ISSUE THREAD

**Issue by eweracs** [github/hubot-sans#28]
The base glyph used in the .ss01 variants of the I are wrong, as it points to the I.ss04 instead of the I:

<img width="717" alt="image" src="https://github.com/github/hubot-sans/assets/51919489/e2bfd30c-a2f7-413d-b9fa-2b9d111c245c">

**Comment by tobiasahlin** [comment]
Fixed in https://github.com/github/hubot-sans/pull/31 🙏
