### ISSUE TITLE
Missing stylistic set variants

### ISSUE THREAD

**Issue by eweracs** [github/hubot-sans#29]
The following stylistic set glyphs are missing:

### ss01 (round dots):
Idieresis.ss01.ss04
Idotaccent.ss01.ss04
Idotbelow.ss01.ss04
Uhorndotbelow.ss01
idotaccent.ss01
udotbelow.ss01
zdotaccent.ss01
idotbelow.dotless.ss01

### ss03 (alternate r):
racute.ss03
rcaron.ss03
rcommaaccent.ss03

### ss04 (serifless I):
Ibreve.ss04

**Comment by tobiasahlin** [comment]
Fixed in https://github.com/github/hubot-sans/pull/31 🙏
